import streamlit as st

st.subheader('Hello, this is "hello_public_1211.py" script from the public repo "shpaksv/tmp_public_repo"')
st.write('This image was generated by AI (https://thispersondoesnotexist.com/)')
st.image('https://thispersondoesnotexist.com/image')
